export const convertToneNumbersToAccents = pinyin => {
    const common = {
        a1: 'ā',
        a2: 'á',
        a3: 'ǎ',
        a4: 'à',
        a5: 'a',
        ai1: 'āi',
        ai2: 'ái',
        ai3: 'ǎi',
        ai4: 'ài',
        ai5: 'ai',
        an1: 'ān',
        an2: 'án',
        an3: 'ǎn',
        an4: 'àn',
        an5: 'an',
        ao1: 'āo',
        ao2: 'áo',
        ao3: 'ǎo',
        ao4: 'ào',
        ao5: 'ao',
        ang1: 'āng',
        ang2: 'áng',
        ang3: 'ǎng',
        ang4: 'àng',
        ang5: 'ang',
        e1: 'ē',
        e2: 'é',
        e3: 'ě',
        e4: 'è',
        e5: 'e',
        er1: 'ēr',
        er2: 'ér',
        er3: 'ěr',
        er4: 'èr',
        er5: 'er',
        en1: 'ēn',
        en2: 'én',
        en3: 'ěn',
        en4: 'èn',
        en5: 'en',
        ei1: 'ēi',
        ei2: 'éi',
        ei3: 'ěi',
        ei4: 'èi',
        ei5: 'ei',
        eng1: 'ēng',
        eng2: 'éng',
        eng3: 'ěng',
        eng4: 'èng',
        eng5: 'eng',
        i1: 'ī',
        i2: 'í',
        i3: 'ǐ',
        i4: 'ì',
        i5: 'i',
        in1: 'īn',
        in2: 'ín',
        in3: 'ǐn',
        in4: 'ìn',
        in5: 'in',
        ing1: 'īng',
        ing2: 'íng',
        ing3: 'ǐng',
        ing4: 'ìng',
        ing5: 'ing',
        o1: 'ō',
        o2: 'ó',
        o3: 'ǒ',
        o4: 'ò',
        o5: 'o',
        ou1: 'ōu',
        ou2: 'óu',
        ou3: 'ǒu',
        ou4: 'òu',
        ou5: 'ou',
        ong1: 'ōng',
        ong2: 'óng',
        ong3: 'ǒng',
        ong4: 'òng',
        ong5: 'ong',
        u1: 'ū',
        u2: 'ú',
        u3: 'ǔ',
        u4: 'ù',
        u5: 'u',
        uv: 'ǚ',
        un1: 'ūn',
        un2: 'ún',
        un3: 'ǔn',
        un4: 'ùn',
        un5: 'un',
    }

    const uncommon = {
        r5: 'r',
        xx5: 'xx',
        E1: 'Ē',
        E2: 'É',
        E3: 'Ě',
        E4: 'È',
        E5: 'E',
        Er1: 'Ēr',
        Er2: 'Ér',
        Er3: 'Ěr',
        Er4: 'Èr',
        Er5: 'Er',
        A1: 'Ā',
        A2: 'Á',
        A3: 'Ǎ',
        A4: 'À',
        A5: 'A',
        An1: 'Ān',
        An2: 'Án',
        An3: 'Ǎn',
        An4: 'Àn',
        An5: 'An',
        Ang1: 'Āng',
        Ang2: 'Áng',
        Ang3: 'Ǎng',
        Ang4: 'Àng',
        Ang5: 'Ang',
        'u:1': 'ǖ',
        'u:2': 'ǘ',
        'u:3': 'ǚ',
        'u:4': 'ǜ',
        'u:5': 'ü',
    }

    for (const key in common) {
        pinyin = pinyin.replace(new RegExp(key, 'g'), common[key])
    }

    for (const key in uncommon) {
        pinyin = pinyin.replace(new RegExp(key, 'g'), uncommon[key])
    }

    return pinyin
}
